### ISSUE TITLE
Can't install plugin on TrueNAS-12.0-U8.1

### ISSUE THREAD

**Issue by trey-k** [jsegaert/iocage-plugin-deluge-pip#10]
Have seen the other few issues related #9 #8 but now am unable to use either fix or follow the commands in the install script to get Deluge working. Noticed that all available packages appear to now be py39-*, with py-libtorrent-rasterbar still possibly missing. Attempted to manually run thru the install script myself but wasn't sure how to put the overlay patches/services in properly

**Comment by jsegaert** [comment]
You'll have to upgrade to at TrueNAS/FreeBSD 13.0 or higher.  See https://github.com/jsegaert/iocage-plugin-deluge-pip/pull/12#issuecomment-1350350363
