### ISSUE TITLE
Can't install plugin on Truenas 13.0U2

### ISSUE THREAD

**Issue by yozart** [jsegaert/iocage-plugin-deluge-pip#11]
Hello, 

When installing Deluge plugin on Truenas 13.0U2, I got following error message. Can you tell me how to proceed please ?

Error: DelugePIP had a failure Exception: RuntimeError Message: pkg error: - py39-libtorrent-rasterbar : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed

**Comment by yozart** [comment]
I found a piece of explanation here: https://www.truenas.com/community/threads/issues-with-deluge-on-truenas-12-u2.92105/#post-713112

Apparently, the current scrip is missing to install a package :
pkg install libtorrent-rasterbar

How can I include it in the script ? or can you do it so everyone can enjoy installing deluge ?

**Comment by jsegaert** [comment]
Yeah, unfortunately, [the python package is currently broken](https://github.com/arvidn/libtorrent/issues/6890) on FreeBSD

**Comment by yozart** [comment]
there is some answer on this last topic but I wasn't able to figure out how to get this working. Maybe you will understood what to do ? Can you please take a look and let me know ?

Thanks a lot for your work&answers anyway

**Comment by AlexanderFeyaerts** [comment]
No solutions for this yet?

**Comment by jsegaert** [comment]
No, package py-libtorrent-rasterbar still doesn't build, unfortunately.

**Comment by yozart** [comment]
proposed a code change based on this comment 
https://www.truenas.com/community/threads/issues-with-deluge-on-truenas-12-u2.92105/#post-713112

**Comment by yozart** [comment]
ok for me
