### ISSUE TITLE
Unable to install deluge plugin on TrueNAS-12.0-U8.1

### ISSUE THREAD

**Issue by bringerer** [jsegaert/iocage-plugin-deluge-pip#8]
When i try to use plugin selector and run its installation it fails with this message
![443](https://user-images.githubusercontent.com/4438582/169642799-a5a294f4-0789-44b7-90c0-d1de5199d5b6.png)

I tried to create new jail over truenas interface and follow commands listed in this post_install.sh script
When i ran "pip install --upgrade pip" it reported that "pip: Command not found." same if i run "pip install deluge"

Instead i ran "pkg install deluge"
This installed deluge and all needed packages. 
I continued with rest f the commands in this script and was able to start deluge web interface.
All worked after that.

**Comment by jsegaert** [comment]
Thanks for letting me know.  

It actually does [install py38-pip](https://github.com/ix-plugin-hub/iocage-plugin-index/blob/master/deluge-pip.json), but something seems wrong with the pip executable.  I added a work-aound, so the plugin should work again... I successfully tested with the default options on TrueNAS-12.0-U8.1

**Comment by bringerer** [comment]
Thanks for quick fix. 
Tested right now on my TrueNAS-12.0-U8.1 and it works now without issues.
