### ISSUE TITLE
Missing packages after upgrading to truenas 13.0-RELEASE

### ISSUE THREAD

**Issue by SobhanAbedi** [jsegaert/iocage-plugin-deluge-pip#9]
Hi. I'm new with containers and jail. After upgrading my truenas installation to 13.0-RELEASE, deluge web-ui wouldn't respond. So I tried upgrading my plugin (with jail) but I get:
`pkg error: - py38-libtorrent-rasterbar : Refusing to fetch artifact and run post_install.sh!`
I also get the same error when I try to create a new deluge plugin.
So I tried updating and making sure all the packages are installed manually from jail shell. But there is no package named "py38-libtorrent-rasterbar". I googled this package and it technically should exist among pkg packages but there wasn't enough information on it that I could compile it from a trusted source.
Then I tried running deluged service manually but I get the following error trace:
```
Starting deluged.
Traceback (most recent call last):
  File "/usr/local/bin/deluged", line 8, in <module>
    sys.exit(start_daemon())
  File "/usr/local/lib/python3.8/site-packages/deluge/core/daemon_entry.py", line 90, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "/usr/local/lib/python3.8/site-packages/deluge/core/daemon.py", line 22,in <module>
    from deluge.core.core import Core
  File "/usr/local/lib/python3.8/site-packages/deluge/core/core.py", line 42, in <module>
    from deluge.core.rpcserver import export
  File "/usr/local/lib/python3.8/site-packages/deluge/core/rpcserver.py", line 21, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Shared object "libffi.so.7" not found, required by "_cffi_backend.cpython-38.so"
```

I also tried upgrading deluge jail through main shell but I get:
```
root@truenas[~]# iocage upgrade -r 13.0-RELEASE deluge-jail
Snapshotting deluge-jail...
Updating plugin INDEX...
Updating plugin artifact...
Cloning git repository

Branch 13.1-RELEASE does not exist at https://github.com/jsegaert/iocage-plugin-deluge-pip.git!
Using "master" branch for plugin, this may not work with your RELEASE
Running upgrade...
12.3-RELEASE is missing 'src.txz', please refetch!
```
Which is reasonable since there are no releases beyond 12.2 branch.

It would be great if you could point me in the right direction.
Thanks.

**Comment by jsegaert** [comment]
Yes, it seems the [py-libtorrent-rasterbar package](https://www.freshports.org/net-p2p/py-libtorrent-rasterbar/) is broken at the moment.

You can either wait until it gets fixed, or switch to the quarterly repo, where it isn't broken yet.  To do this, you can manually install the plugin as per the below:
```
fetch https://raw.githubusercontent.com/jsegaert/iocage-my-plugins/master/deluge-pip.json
iocage fetch -P deluge-pip.json  -n deluge-jail
```
I tested this successfully installs on TrueNAS-12.0-U8.1

**Comment by SobhanAbedi** [comment]
thanks
